# Generated by Django 6.0.5 on 2026-06-15 17:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dietary_preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='illness_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_currently_ill',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pregnancy_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='health_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list),
        ),
    ]
