# Generated by Django 6.0.5 on 2026-06-15 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('weights_path', models.CharField(max_length=255)),
                ('mae_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('training_data_size', models.IntegerField()),
                ('is_production', models.BooleanField(default=False)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_barcode', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('user_age_at_scan', models.IntegerField()),
                ('user_conditions_at_scan', models.JSONField()),
                ('user_allergies_at_scan', models.JSONField()),
                ('additives_found', models.JSONField()),
                ('per_additive_scores', models.JSONField()),
                ('final_risk_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('risk_label', models.CharField(max_length=50)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
