# Generated by Django 6.0.5 on 2026-06-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_userscanhistory_delete_inferencelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InferenceLog',
        ),
    ]
