# Generated by Django 6.0.5 on 2026-06-19 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_delete_inferencelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField(blank=True, default='')),
                ('chat_history', models.JSONField(blank=True, default=list)),
                ('temp_barcode', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_userchatcontext',
            },
        ),
    ]
