"use client"

import { motion } from "framer-motion"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground py-12 px-4 sm:px-6 lg:px-8 font-inter">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="max-w-4xl mx-auto"
      >
        <Link href="/">
          <Button variant="ghost" className="mb-8 -ml-4 text-muted-foreground hover:text-foreground">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
        </Link>
        
        <h1 className="text-4xl font-bold font-syne mb-2">BioDose — Terms and Conditions</h1>
        <p className="text-muted-foreground mb-8 text-sm border-b border-border pb-8">
          BIODOSE APPLICATION — TERMS AND CONDITIONS OF USE<br/>
          Version 1.0 | Effective Date: [Date of Launch]
        </p>

        <div className="prose prose-slate dark:prose-invert max-w-none space-y-8 text-sm md:text-base leading-relaxed">
          <p>
            Please read these Terms and Conditions carefully before using the BioDose application. By creating an account and checking the acceptance box during registration, you acknowledge that you have read, understood, and agree to be legally bound by all terms stated herein. If you do not agree to any part of these terms, you must not use this application.
          </p>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 1 — NATURE OF THE SERVICE AND LIMITATION OF MEDICAL AUTHORITY</h2>
            <p>
              BioDose is a food safety analysis and personalized nutrition guidance tool developed as a technology-driven decision support system. The application provides risk assessments based on publicly available food additive safety data sourced from internationally recognized regulatory bodies including the European Commission E-number classification system, the United States Food and Drug Administration Generally Recognized as Safe database, and the WHO/FAO Joint Expert Committee on Food Additives. BioDose does not constitute a medical device, does not provide medical diagnosis, and does not replace the advice, consultation, or prescription of any licensed medical professional, registered dietician, allergist, or certified nutritionist. The risk scores and recommendations generated by BioDose are probabilistic suggestions derived from population-level data and mathematical aggregation algorithms. They are not personalized clinical assessments. Any decision regarding diet, food consumption, medication interaction, or health management that a user makes based on BioDose output is made entirely at the user's own risk and discretion. BioDose and its developers expressly disclaim any responsibility for health outcomes, medical events, allergic reactions, adverse drug-food interactions, or any other consequence arising from a user's reliance on the application's output in place of professional medical advice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 2 — ACCURACY AND COMPLETENESS OF USER-PROVIDED HEALTH PROFILE DATA</h2>
            <p>
              The risk analysis generated by BioDose is entirely dependent on the accuracy, completeness, and truthfulness of the health profile information provided by the user during account registration and any subsequent profile updates. This includes but is not limited to the user's declared age, body weight, gender, health conditions, known allergies, dietary restrictions, current medications, pregnancy status, and any temporary illness states. BioDose has no mechanism to independently verify, validate, cross-check, or authenticate any information that a user enters into their health profile. The application processes user-provided data in good faith as factual input and generates risk assessments accordingly. If a user omits, incorrectly states, underestimates, or deliberately misrepresents any aspect of their health profile — whether intentionally or due to lack of self-knowledge — the resulting risk assessments will be based on incomplete or inaccurate information and may not reflect the user's actual risk. BioDose bears no liability whatsoever for inaccurate risk assessments, missed warnings, false clearances, or any health consequences that arise directly or indirectly from a user's failure to provide complete and accurate health profile data. The responsibility for the accuracy of profile information rests entirely and exclusively with the user.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 3 — THE UNDISCLOSED ALLERGY AND UNDIAGNOSED CONDITION EXEMPTION</h2>
            <p>
              A specific and critical limitation of BioDose is that the system can only flag risks for health conditions and allergies that the user has explicitly declared in their active health profile. If a user has an allergy, sensitivity, intolerance, or health condition that they have not disclosed in their profile — whether because they are unaware of it, have not been formally diagnosed, chose not to disclose it, or simply forgot to include it — BioDose will not flag additives or ingredients that may be harmful for that undisclosed condition. For example, a user with an undiagnosed gluten sensitivity who does not select Celiac Disease or Gluten Sensitivity in their profile will receive risk assessments that do not account for gluten-related additives. If that user subsequently consumes a product that BioDose assessed as low-risk for their declared profile and experiences an adverse reaction attributable to the undisclosed condition, this constitutes user negligence and not application failure. BioDose explicitly disclaims any liability for adverse outcomes caused by conditions, allergies, or sensitivities not declared in the user's active health profile at the time of scanning. Users are strongly advised to consult a medical professional to obtain a complete diagnosis of their health conditions before creating or updating their BioDose profile.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 4 — PROBABILISTIC RISK SCORING AND ITS INHERENT UNCERTAINTY</h2>
            <p>
              The risk scoring system in BioDose operates on a probabilistic continuous scale from 0.1 to 0.9, where 0.1 represents the lowest assessed risk and 0.9 represents the highest assessed risk for a given user profile and product combination. The deliberate choice to use a scale anchored at 0.1 rather than 0.0, and at 0.9 rather than 1.0, reflects a foundational principle of this application — that absolute safety and absolute danger cannot be claimed for any food substance for any human individual. Human biological response to food additives is subject to individual genetic variation, microbiome composition, cumulative dietary exposure, concurrent medication effects, and numerous other factors that no algorithmic system can fully account for. A score of 0.1 does not mean the product is guaranteed safe for the user. A score of 0.9 does not mean the product will certainly cause harm. These scores represent the application's best algorithmic estimate of population-level risk adjusted for the user's declared profile. BioDose makes no warranty, express or implied, that any risk score represents a complete, final, or clinically accurate assessment of safety or danger for any specific individual. Users must interpret scores as probabilistic guidance only and must not treat any score as a definitive medical clearance or prohibition.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 5 — THE CUMULATIVE RISK ALGORITHM AND ITS MATHEMATICAL FOUNDATIONS</h2>
            <p>
              The cumulative risk score generated by BioDose is calculated using a deterministic mathematical algorithm designed around two established toxicological phenomena — Single-Trigger Dominance and Synergistic Toxicity, also referred to as the Cocktail Effect. Single-Trigger Dominance ensures that a single severely flagged additive relevant to a critical user condition such as a life-threatening allergy cannot be mathematically diluted by the presence of many low-risk ingredients in the same product. Synergistic Toxicity accounts for the compounding effect of multiple additives acting on the same health condition or on multiple simultaneous health conditions. The algorithm assigns tiered weights to user health conditions where critical conditions such as allergies and anaphylaxis-risk conditions carry a weight of 1.0, chronic long-term conditions carry a weight of 0.6, and transient or acute conditions carry a weight of 0.3. Intra-condition risk is calculated per condition using an average additive score compounded by a synergy factor proportional to the number of flagged additives. A cross-condition penalty is then applied to simulate systemic stress from multiple simultaneously active conditions. The final score is strictly capped at 1.0. While this algorithm is grounded in established principles from environmental toxicology and food science including adaptations of the WHO Hazard Index methodology, it remains a computational model and not a clinical tool. The algorithm's parameters, tier classifications, and synergy factors were determined by the development team based on available literature and are subject to revision as the application evolves. BioDose does not guarantee that the algorithm perfectly replicates clinical risk assessment methodology and acknowledges that edge cases, rare conditions, and unusual additive combinations may produce outputs that deviate from what a medical expert would assess.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 6 — DATASET ACCURACY, SOURCE LIMITATIONS, AND THIRD PARTY DATA DEPENDENCY</h2>
            <p>
              The additive risk dataset underlying BioDose's risk assessments was compiled from publicly available international food safety databases including JECFA, EFSA, FSSAI, and PubChem, supplemented by domain-expert curation. While every reasonable effort has been made to ensure the accuracy and currency of this dataset, BioDose cannot guarantee that it is free from errors, omissions, outdated classifications, or incomplete entries. Food additive safety classifications are periodically revised by regulatory bodies as new scientific evidence emerges. BioDose's dataset may not always reflect the most current regulatory status of every additive in real time. Additionally, product ingredient data is sourced from the Open Food Facts API, a community-contributed open database. BioDose does not independently verify the accuracy, completeness, or currency of product ingredient lists retrieved from Open Food Facts. Products may have been reformulated after their Open Food Facts entry was last updated. Ingredient lists may contain transcription errors introduced by community contributors. Certain additives may be listed under regional or trade names that the application's matching system does not recognize. BioDose disclaims all liability for inaccurate risk assessments arising from errors, omissions, or outdated information in third-party data sources including but not limited to the Open Food Facts database, JECFA, EFSA, and FSSAI publications. 
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 7 — USER ACCOUNT SECURITY AND CREDENTIAL RESPONSIBILITY</h2>
            <p>
              BioDose implements industry-standard security protocols for the protection of user accounts and data. Authentication is managed using JSON Web Tokens with short-lived access tokens and httpOnly cookie-stored refresh tokens. User passwords are never stored in plain text and are hashed using Django's built-in PBKDF2 password hashing algorithm with a randomly generated salt. Database access is protected using Row Level Security policies enforced at the database layer through Supabase PostgreSQL, ensuring that each user can only access their own data. API endpoints are protected against unauthorized access through JWT Bearer token validation on every authenticated request. Session tokens are automatically invalidated upon logout through server-side token blacklisting using Redis. Despite these measures, BioDose cannot guarantee absolute security against all possible attack vectors. No internet-connected system can make that guarantee. BioDose is not liable for unauthorized account access that results from the user's own actions, including but not limited to sharing login credentials with another person, leaving the application open and unattended on a shared or public device, using a weak or reused password, failing to log out on a shared device, responding to phishing attempts that impersonate BioDose, or allowing another person to observe their login credentials. The responsibility for maintaining the security and confidentiality of account credentials rests solely with the account holder. Users must notify BioDose immediately if they suspect unauthorized access to their account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 8 — DATA COLLECTION, STORAGE, AND USE FOR MODEL IMPROVEMENT</h2>
            <p>
              By using BioDose and scanning products, users consent to the collection and storage of anonymized inference data generated during their use of the application. This data includes the product scanned, the additive risk scores generated, the final cumulative risk score, a snapshot of the user's health conditions at the time of scanning (not including personally identifiable information such as name or email), and the model version that produced the result. This anonymized inference data is stored in a secure backend database and is used exclusively for the purpose of training and improving BioDose's risk scoring models over time, including shadow models that train in the background on accumulated usage data to improve future risk prediction accuracy. This data is never sold to third parties, never shared with food manufacturers, advertisers, or marketing entities, and is not used for any purpose other than improving the application's algorithmic accuracy. Users may request deletion of all their stored data at any time by contacting BioDose support, after which their data will be permanently removed from all databases within 30 days, in accordance with applicable data protection regulations. The anonymized inference logs used for model training cannot be reverse-engineered to identify individual users.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 9 — SHADOW MODEL TRAINING AND ALGORITHMIC EVOLUTION DISCLOSURE</h2>
            <p>
              BioDose employs a continuous learning architecture in which shadow models — alternative versions of the risk scoring algorithm — are trained in the background on anonymized real-world usage data accumulated through the application's inference logs. These shadow models are evaluated against the current production model on a held-out validation dataset. A shadow model is only promoted to replace the production model if it demonstrably outperforms the current model by a statistically meaningful margin as measured by Mean Absolute Error on validation data. Model promotions are logged in a model registry with timestamps and performance metrics. Users should be aware that the specific risk scores generated for a given product and user profile combination may change over time as the underlying model evolves. A product that received a risk score of 0.4 under one model version may receive a score of 0.5 or 0.3 under a subsequent version that has been trained on more data and refined its prediction accuracy. BioDose does not guarantee that risk scores will be consistent across model versions and is not liable for any decision a user made based on a score generated by a previous model version that differs from the score the current model would generate for the same input.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 10 — PRODUCT COVERAGE LIMITATIONS AND UNRECOGNIZED PRODUCT DISCLAIMER</h2>
            <p>
              BioDose retrieves product data from the Open Food Facts database which, while extensive, does not contain every packaged food product available globally or in every regional market. Indian packaged food products in particular may have limited or incomplete coverage in the Open Food Facts database. When a scanned barcode is not found in the Open Food Facts database, BioDose will inform the user that product data is unavailable and no risk assessment will be generated. The absence of a risk assessment for an unrecognized product does not mean the product is safe. It means the application does not have sufficient data to assess it. Similarly, when a product is found in the database but has an incomplete ingredient list — for example, missing additive information or having ingredients listed in a language that the application's normalization layer cannot parse — the resulting risk assessment may be incomplete or inaccurate. BioDose is not liable for health consequences arising from the user's consumption of products that the application could not fully assess due to database coverage limitations, incomplete product entries, or language parsing failures. Users are advised to exercise independent caution with products that return incomplete assessments and to read the physical product label directly.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 11 — CHILDREN, PREGNANT WOMEN, AND VULNERABLE POPULATION SPECIAL NOTICE</h2>
            <p>
              BioDose includes specific risk scoring parameters for vulnerable populations including infants aged 0 to 5 years, children aged 6 to 12 years, teenagers aged 13 to 17 years, pregnant women, breastfeeding women, and elderly individuals aged 60 and above. However, these parameters are based on generalized population-level safety thresholds derived from regulatory literature and do not account for individual clinical complexity within these groups. Pregnant women, in particular, are subject to rapidly changing physiological conditions, medication regimens, and dietary restrictions that may vary week by week throughout pregnancy and that BioDose's static profile system cannot track dynamically. Parents or guardians creating profiles for children must ensure that all health conditions, allergies, and dietary restrictions for the child are accurately entered. BioDose explicitly advises that its assessments for children, pregnant women, breastfeeding women, and elderly individuals should be treated with heightened caution and should be validated against the recommendations of a qualified healthcare provider. BioDose is not responsible for adverse outcomes in vulnerable population members whose profiles were inaccurately or incompletely set up, or whose dynamic health status changed after their profile was last updated.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 12 — MEDICATION INTERACTION LIMITATIONS</h2>
            <p>
              BioDose's risk scoring system includes a medication interaction parameter that flags additives known to interact with broad drug classes such as antihypertensives, antidiabetics, anticoagulants, MAO inhibitors, immunosuppressants, and similar categories. Users declare their medications by drug class rather than by specific drug name. This approach is intentional — BioDose is not a pharmacological database and does not claim to have comprehensive drug-specific interaction data. The medication interaction flags in BioDose's dataset are based on known class-level interactions documented in publicly available pharmacological and food science literature. BioDose does not account for interactions specific to particular branded or generic drugs within a class, drug dosage effects, polypharmacy interactions between multiple drugs a user may be taking, recently approved medications not yet documented in available literature, or interactions between food additives and over-the-counter medications not declared in the user's profile. BioDose is not a substitute for pharmacist or physician guidance on food-drug interactions. Users on complex medication regimens, recently started on new medications, or undergoing treatment for serious conditions must consult their prescribing physician or pharmacist before using BioDose's risk assessments as any form of dietary guidance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 13 — NO WARRANTY OF UNINTERRUPTED SERVICE OR DATA AVAILABILITY</h2>
            <p>
              BioDose is provided on an as-is and as-available basis. The developers make no warranty, express or implied, that the application will be available without interruption, free from technical errors, free from bugs, or that data retrieved from third-party APIs will always be accurate and current. Planned and unplanned maintenance, server downtime, third-party API outages including the Open Food Facts API, database connection failures, and other technical issues may render the application temporarily unavailable or cause individual features to malfunction. BioDose is not liable for any harm, loss, or inconvenience caused by service interruption, data unavailability, API failure, or any other technical disruption. Users should not rely on BioDose as the sole or primary means of assessing food safety for critical health situations. In situations where a user's health condition requires strict dietary management — such as severe food allergies, celiac disease, or phenylketonuria — the user must always rely on direct physical examination of the product label and professional medical guidance, independent of and in addition to any assessment provided by BioDose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 14 — CHANGES TO TERMS, DATASET, AND ALGORITHM</h2>
            <p>
              BioDose reserves the right to modify these Terms and Conditions, update the underlying additive risk dataset, revise the risk scoring algorithm, and change any feature of the application at any time without prior individual notice to users. Changes to these Terms and Conditions will be posted within the application with an updated effective date. Continued use of BioDose after changes are posted constitutes the user's acceptance of the revised terms. Changes to the dataset or algorithm may result in different risk assessments being generated for the same product and user profile compared to previous versions of the application. BioDose is not obligated to notify users of changes to internal algorithmic parameters or dataset entries and is not liable for any decision made by a user based on a risk assessment generated under a previous version of the algorithm or dataset that differs from what the current version would generate.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 15 — GOVERNING LAW AND DISPUTE RESOLUTION</h2>
            <p>
              These Terms and Conditions are governed by the laws of the Republic of India. Any dispute arising from the use of BioDose, these Terms and Conditions, or any health or safety claim related to the application's output shall first be subject to a mandatory 60-day good faith negotiation period between the user and the BioDose development team. If the dispute is not resolved through negotiation, it shall be referred to binding arbitration under the Arbitration and Conciliation Act, 1996 of India. The seat of arbitration shall be Bangalore, Karnataka, India. The language of arbitration shall be English. By accepting these Terms and Conditions, the user waives any right to bring a class action lawsuit against BioDose or its developers. Users also expressly acknowledge that BioDose is a technology tool and not a medical service provider and that health outcome claims are therefore outside the scope of product liability as defined under the Consumer Protection Act, 2019 of India to the extent permitted by applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 16 — INDEMNIFICATION</h2>
            <p>
              The user agrees to indemnify, defend, and hold harmless BioDose and its developers, contributors, advisors, and affiliated academic institution from and against any and all claims, damages, losses, liabilities, costs, and expenses including reasonable legal fees arising out of or relating to the user's violation of these Terms and Conditions, the user's provision of inaccurate or incomplete health profile information, the user's reliance on BioDose's risk assessments in place of professional medical advice, the user's negligent or unauthorized use of the application, the user's sharing of account credentials with third parties, or any claim by a third party resulting from the user's use of the application. This indemnification obligation survives termination of the user's account and these Terms and Conditions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 17 — ACADEMIC AND RESEARCH CONTEXT DISCLOSURE</h2>
            <p>
              BioDose was developed as part of an interdisciplinary product development project by engineering students. The underlying medical risk dataset was curated with domain expertise from chemical engineering collaborators using publicly available international food safety data from JECFA, EFSA, FSSAI, and PubChem. The risk scoring algorithm was designed following principles drawn from WHO environmental toxicology methodology and peer-reviewed food science literature. While the application has been built with serious intent toward accuracy and medical relevance, it has not been peer-reviewed as a clinical tool, has not undergone clinical validation trials, has not been approved by any medical regulatory authority, and has not been certified as a medical device by CDSCO or any equivalent body. Users must understand that BioDose represents a technology prototype built on the best available public data and sound engineering principles, but that it has not reached the standard of validation required for certified medical or clinical use. The application is intended to promote food safety awareness and informed consumer decision-making, not to provide clinical guidance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 18 — ACCOUNT TERMINATION AND DATA RETENTION</h2>
            <p>
              BioDose reserves the right to suspend or permanently terminate a user's account without prior notice if the user is found to be misusing the application, attempting to reverse-engineer the algorithm, attempting to access other users' data, submitting false or misleading health profile information with intent to manipulate risk outputs, or violating any provision of these Terms and Conditions. Upon account termination, the user's personally identifiable data including name, email, and health profile will be deleted from the primary database within 30 days. Anonymized inference log records that do not contain personally identifiable information may be retained for model training purposes as they cannot be attributed to the terminated account. Users who wish to voluntarily delete their account and all associated data may do so through the account settings page or by contacting support, and deletion will be completed within 30 days of the verified request.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-4">TERM 19 — ACCEPTANCE OF TERMS AS CONDITION OF USE</h2>
            <p>
              Use of BioDose is conditional upon explicit acceptance of all terms stated in this document. During account registration, users will be required to check a clearly labeled checkbox confirming that they have read and agree to these Terms and Conditions in their entirety. Checking this box constitutes a binding legal acknowledgment that the user understands the probabilistic and non-clinical nature of BioDose's risk assessments, accepts full responsibility for the accuracy of their health profile data, waives the right to hold BioDose or its developers liable for health outcomes arising from the use of the application, and agrees to all other terms stated herein. Users who do not agree to any part of these terms must not proceed with registration and must not use the application. The acceptance event, including a timestamp and the user's IP address, will be recorded in the BioDose database as evidence of informed consent.
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-border text-sm text-muted-foreground">
          <p>BioDose Development Team</p>
          <p>Contact: sirikumarc.ai23@rvce.edu.in</p>
          <p>Last Updated: [Today's date]</p>
        </div>
      </motion.div>
    </div>
  )
}
